name: Build .NET 8 Template

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-path:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Show project name
        run: |
          echo ""                                               
          echo "  | |                         (_)             "
          echo "  | |     ___  __ _ _ __ _ __  _ _ __   __ _  "
          echo "  | |    / _ \/ _` | '__| '_ \| | '_ \ / _` | "
          echo "  | |___|  __/ (_| | |  | | | | | | | | (_| | "
          echo "  |______\___|\__,_|_|  |_| |_|_|_| |_|\__, | "
          echo "                                        __/ | "
          echo "                                       |___/  " 
          echo ""                                               
          echo " Setting up ${{ inputs['project-name'] }}"
  build:
    runs-on: ubuntu-latest
    env:
      CSPROJ_PATH: ${{ github.event.inputs.project-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
            dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore $CSPROJ_PATH
      - name: Build
        run: dotnet build $CSPROJ_PATH --no-restore 
      - name: Test
        run: dotnet test $CSPROJ_PATH --no-build --verbosity normal
