name: Build .NET 8 Template

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-path:
        required: true
        type: string
permissions:
  packages: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Show project name
        run: |
          echo ""                                               
          echo "  | |                         (_)             "
          echo "  | |     ___  __ _ _ __ _ __  _ _ __   __ _  "
          echo "  | |    / _ \/ _` | '__| '_ \| | '_ \ / _` | "
          echo "  | |___|  __/ (_| | |  | | | | | | | | (_| | "
          echo "  |______\___|\__,_|_|  |_| |_|_|_| |_|\__, | "
          echo "                                        __/ | "
          echo "                                       |___/  " 
          echo ""                                               
          echo " Setting up ${{ inputs['project-name'] }}"
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
            dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}/${{ inputs.project-name }}.csproj
      - name: Build
        run: dotnet build ${{ inputs.project-path }}/${{ inputs.project-name }}.csproj --no-restore -c Release
      - name: Test
        run: dotnet test ${{ inputs.project-path }}/${{ inputs.project-name }}.csproj --no-build --verbosity normal
      - name: Generate version number
        id: version
        run: echo "VERSION=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: Generate NuGet Package
        run: dotnet pack ${{ inputs.project-path }}/${{ inputs.project-name }}.csproj --configuration Release --no-build --output ./nupkgs -p:Version=${{ steps.version.outputs.version }}   
      - name: Upload do pacote como artifact
        uses: actions/upload-artifact@v4
        with:
         name: pacote-nuget
         path: ./nupkgs/*.nupkg
    
  pack:
    runs-on: ubuntu-latest
    environment: production 
    needs: build
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Baixar os binários do build
        uses: actions/download-artifact@v4
        with:
          name: pacote-nuget
          path: ./nupkgs
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}
      - name: Publish NuGet Package
        run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SOURCE }} --skip-duplicate
  
